name = "wmt-junior"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["*/5 * * * *"]

[[r2_buckets]]
binding = "VOICE_BUCKET"
bucket_name = "wmt-junior-voices"

[vars]
ENVIRONMENT = "production"
SUPABASE_URL = "https://jdpvbpiiwrmrykviiqhw.supabase.co"
ALLOWED_USER_IDS = "1524908105, 6678270537"
ADMIN_ID = "1524908105"
